# Generated by Django 5.1.7 on 2025-03-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
