# Generated by Django 5.1.6 on 2025-02-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='佣金率')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='佣金金额')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.order')),
            ],
        ),
    ]
